name: task
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
  fluttercontactpicker: ^4.3.0
  fluttertoast: ^8.2.4
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Spirit-Of-Doha
      fonts:
        - asset: assets/fonts/ArbFONTS-Spirit-Of-Doha-Bold.otf
          weight: 700
#        - asset: assets/fonts/ArbFONTS-URW-DIN-Arabic-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/ArbFONTS-URW-DIN-Arabic.ttf
#          weight: 400
#        - asset: assets/fonts/ArbFONTS-URW-DIN-Arabic-Light.ttf
#          weight: 300
#      fonts:
#        - asset: assets/fonts/
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
